# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Rohan_Test_Agent

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: HCL AppScan Enterprise@2
  inputs:
    ServiceEndPointAse: 'ASE_Creds_Win37_2021'
    jobName: 'ASENew'
    folderId: 12
    templateId: 7
    testPolicyId: 8